### ISSUE TITLE
AutoTaunt?

### ISSUE THREAD

**Issue by twdnhfr** [X-Xeer-X/NerdPack-Xeer#1]
Hi thanks for your awesome routines, im using them over my own now for prot warrior.

One Question, why is AutoTaunt commented out in core.lua? Does it work?

btw your arms rota is missing whirlwind with talent 3,1 which replaces slam

**Comment by Q-U-I-N** [comment]
Yea AutoTaunt working,  in my core  taunt was just for testing (will remove it in next push) now its using build in from general NerdPack.

Fixed WW in arms, test it and report it back if it works:)

**Comment by twdnhfr** [comment]
ill test this evening, thanks a lot! Do you have any plans for healing routines?

**Comment by twdnhfr** [comment]
arms does work good now - but it seems that it does not use orc racial correctly. I tried alternating the cast without any condition but it doesnt work either. Can maybe be a problem with nerdpack?

**Comment by Q-U-I-N** [comment]
i will take a look on racial abilities later
