### ISSUE TITLE
area.enemies

### ISSUE THREAD

**Issue by gongmang1** [X-Xeer-X/NerdPack-Xeer#6]
fire mage running well
area.enemies can't work

LASTEST NeP core files

**Comment by gongmang1** [comment]
fire mage's
Meteor can't castground,and if use EWT, target.ground into mouseover.ground,can not cast@ target

**Comment by gongmang1** [comment]
or 
the NerdPack is update very frequent,
can you upload the NerdPack version you are using,
thx

**Comment by twdnhfr** [comment]
@gongmang1 try using the latest version, as far as i know Xeer is also developing against 1.6 / the latest
There have been some fixes to area.enemies these days to NerdPack

**Comment by gongmang1** [comment]
enUS client is working, but zhCN not working

**Comment by MrTheSoulz** [comment]
You need to add it to the locale file, it will work
